### ISSUE TITLE
Current trick for handling duplicates can lead to trouble with manual re-init

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-LearningFramework#106]
The current way of how each duplicate gets its own duplication number is based on a global variable getting incrementing when each duplicate gets initialised. Then, training is only performed by the duplicate which was the first. 

This will cause the PR to fail if inside the GUI the user manually re-initialises the PR, thus incrementing the counter. We need to move the counter incrementing into custom duplication code.

**Comment by ianroberts** [comment]
Alternatively just add code in `reInit()` to clear the counter, so that a manual re-init is treated the same as the initial `init` rather than the same as a duplication.

**Comment by johann-petrak** [comment]
Current implementation uses custom duplication to do this, fixed by 0147dec62f6c694a81180965c09eccfb530238da
