### ISSUE TITLE
Xingyi's bug report

### ISSUE THREAD

**Issue by deansong** [GateNLP/gateplugin-LearningFramework#109]
I notice several bugs may need to remove in next version
1. Copy model from GPU machine to CPU only cause cuda error:    raise RuntimeError(‘Attempting to deserialize object on a CUDA ’ (detail in slack)
  -- current solution is del state['optimizer'] in the __getstate__ 
  seems removed the cuda error

2. Performance difference when copy model from GPU machine to CPU only machine.
    copied file: FileJsonPyTorch.model.module.pytorch 
    about 10% accuracy difference in same test corpus.
    GATE version is same but pytorch is different 0.4.1 (gs8) vs 1.0.1 (xingyi's mac)

3. Path error when copy FileJsonPyTorch.model.wrapper.pickle
    - the meta file path is stored in FileJsonPyTorch.model.wrapper.pickle, this cause can't find file error when copy to different machine

**Comment by johann-petrak** [comment]
1) corresponds to https://github.com/GateNLP/gate-lf-pytorch-json/issues/38
2) corresponds to https://github.com/GateNLP/gate-lf-pytorch-json/issues/41 
3) corresponds to https://github.com/GateNLP/gate-lf-pytorch-json/issues/39

**Comment by johann-petrak** [comment]
1) and 3) should be fixed in the latest snapshot but need testing.

**Comment by johann-petrak** [comment]
Tested and all three issues seem to be solved.
